## Implementação das Portas Lógicas OR, AND e XOR a partir de um Perceptron, uma MLP (com funções básicas do Python) e uma rede neural e com o TensorFlow
##### Implementado por: Augusto Modesto

#### Algumas observações quanto ao exercício:

##### 1- Foram utilizadas apenas funções básicas do python para implementação do algorítmo, com exceção da biblioteca numpy.
##### 2- Foram utilizados métodos atômicos nas classes criadas para facilitar possíveis testes unitários.
##### 3- Foram criadas três classes para realizar o exercício.
##### 4- Foram criados três casos de testes (OR, AND e XOR) para testar o código do Perceptron e da MLP.
##### 5- Os mesmos três casos de testes foram replicados, ao final, utilizando a biblioteca tensorflow.

### Bibliotecas essenciais para construção das Classes

In [1]:
import numpy as np # Utilizado para realizar operações com matrizes e vetores

### Desafio 1: Criação de um Perceptron para testar com as Portas Lógicas OR e AND 

#### Classe Perceptron para trabalhar com os casos de testes OR e AND

In [2]:
class Perceptron:
    '''
    Essa classe contém a implementação dos principais métodos de um neurônio digital Perceptron.
    
    Lista de Atributos:
        qtd_inputs: é a quantidade de inputs que iniciarão o perceptron.
        qtd_epocas: é a quantidade de iterações que a rede realizará para aprender os padrões presentes nos
                     dados de entrada.
        taxa_aprendizagem: é a taxa da velocidade na qual a descida gradiente ocorre.
        weight: são os pesos atribuidos as entradas dos perceptrons.                
    
    Lista de Métodos Públicos:
        __init__: inicializa as variáveis da classe.
        fit: treina o modelo com base no dataset de entrada.
        predict: prediz valores com base no treino realizado com a função .fit().
     
    Lista de Métodos Privados:
        N/A
    '''
    
    def __init__(self, qtd_inputs = 2, qtd_epocas = 100, taxa_aprendizagem = 0.5):
        '''
        Método público que inicializa a instância da classe.
        Não há retorno para este método.
        
        Args:
            qtd_inputs(int): é a quantidade de inputs do perceptron. Por default essa variável é inicializada
                        com o valor 2.
            
            qtd_epocas(int): é a quantidade de épocas que serão processadas pela rede neural. Por default essa
                        variável é inicializada com o valor 100.
                        
            taxa_aprendizagem(float): é a taxa de aprendizagem do perceptron. É responsável pela velocidade na qual 
                               a descida gradiente acontece. Por default essa variável é inicializada com o
                               valor 0.5.
                               
            weight(list): são os pesos dos atribuidos as entradas dos perceptrons para realizar seu treinamento.
        
        Returns:
            N/A
        '''
        # Atributos base da classe
        self.qtd_inputs = qtd_inputs
        self.qtd_epocas = qtd_epocas        
        self.taxa_aprendizagem = taxa_aprendizagem
        
        # Os pesos são iniciados com uma lista de 0's
        self.weight = np.zeros(qtd_inputs + 1)
    
    def fit(self, train_inputs, labels):
        '''
        Método público para realizar o treino da rede (perceptrons).
        Não há retorno para este método.
        
        Args:
            train_inputs(list): é uma lista contendo os valores de input para a rede neural.
            
            labels(list): é uma lista contendo os labels da saída da rede neural.
            
        Returns:
            N/A
        '''
        for i in range(self.qtd_epocas):
            for inputs, label in zip(train_inputs, labels):
                predicao = self.predict(inputs)       
                self.weight[1:] += self.taxa_aprendizagem * (label - predicao) * inputs
                self.weight[0] += self.taxa_aprendizagem * (label - predicao)
    
    def predict(self, inputs):
        '''
        Método público que prediz o resultado do valor informado conforme treino realizado na rede neural
        com o método .fit().
        Retorna a label correspondente ao valor de entrada.
        
        Args:
            inputs(list): é uma lista que corresponde aos valores de entrada que se deseja realizar a predição.
        
        Return:
            Retorna 1 para o caso do resultado da função de ativação ser maior que 0. E retorna 0 quando o
            resultado da função de ativação é menor ou igual a 0.
        '''
        somatorio = np.dot(inputs, self.weight[1:]) + self.weight[0]
        return 1 if somatorio > 0 else 0   

### Realização dos testes da classe criada (Perceptron)

#### Caso de Teste 1: Testando a Porta Lógica OR

In [3]:
# Instanciando o Perceptron a partir do código criado
PCT = Perceptron()

In [4]:
# Populando os valores de entrada da porta lógica OR
x_train = np.array([[0,0],[0,1],[1,0],[1,1]])

# Populando os valores de saída da porta lógica OR
y_train = np.array([0, 1, 1, 1])

In [5]:
# Realizando o treino do Perceptron
PCT.fit(x_train, y_train)

In [6]:
# Testando o resultado para o caso [0,0]
x_test = np.array([0, 0])
valor_predito = PCT.predict(x_test)
print('Valor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [0,1]
x_test = np.array([0, 1])
valor_predito = PCT.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [1,0]
x_test = np.array([1, 0])
valor_predito = PCT.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [1,1]
x_test = np.array([1, 1])
valor_predito = PCT.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

Valor predito de [0 0] é: 0

Valor predito de [0 1] é: 1

Valor predito de [1 0] é: 1

Valor predito de [1 1] é: 1


#### Caso de Teste 2: Testando a Porta Lógica AND

In [7]:
# Instanciando o Perceptron a partir do código criado
PCT_2 = Perceptron()

In [8]:
# Populando os valores de entrada da porta lógica AND
x_train = np.array([[0,0],[0,1],[1,0],[1,1]])

# Populando os valores de saída da porta lógica AND
y_train = np.array([0, 0, 0, 1])

In [9]:
# Realizando o treino do Perceptron
PCT_2.fit(x_train, y_train)

In [10]:
# Testando o resultado para o caso [0,0]
x_test = np.array([0, 0])
valor_predito = PCT_2.predict(x_test)
print('Valor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [0,1]
x_test = np.array([0, 1])
valor_predito = PCT_2.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [1,0]
x_test = np.array([1, 0])
valor_predito = PCT_2.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [1,1]
x_test = np.array([1, 1])
valor_predito = PCT_2.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

Valor predito de [0 0] é: 0

Valor predito de [0 1] é: 0

Valor predito de [1 0] é: 0

Valor predito de [1 1] é: 1


### Desafio 2: Criação de uma MLP para testar com as Portas Lógicas XOR 

#### Classe MultilayersPerceptron (MLP) para trabalhar com o caso de teste XOR

In [11]:
class MultilayersPerceptron():
    '''
    Essa classe contém a implementação dos principais métodos de uma rede neural de multicamadas (MLP).
    Essa classe utiliza o função de ativação sigmoid e sua derivada. E o método de aprendizagem aplicado
    a MLP é o backpropagation.
    
    Lista de Atributos:
        qtd_inputs: é a quantidade de variáveis de entrada para a MLP.
        qtd_camadas: é a quantidade de camadas da MLP.
        qtd_saidas: é a quantidade de saídas que serão geradas na MLP.
        qtd_epocas: é a quantidade de iterações que a rede realizará para aprender os padrões presentes nos
                     dados de entrada. 
        taxa_aprendizagem: é a taxa da velocidade na qual a descida gradiente ocorre.
        weight_1: são os pesos aplicados as camadas ocultas (hidden layers) da MLP.
        weight_2: são os pesos aplicados a última camada da MLP.
        bias_hidden: são os bias aplicados as camadas ocultas (hidden layers) da MLP.
        bias_output: é o bia aplicado a última camada da MLP.
        sig: é a função de ativação da MLP. O cálculo implementado corresponde a função sigmoid.
        dsig: é a derivada da função de ativação.               
    
    Lista de Métodos Públicos:
        __init__: inicializa as variáveis da classe.
        fit: treina o modelo com base no dataset de entrada.
        predict: prediz valores com base no treino realizado com a função .fit().
        calcula_erro: calcula os erros do output e das hidden layer. 
        backpropagation: realiza a aprendizam do neurônio (ajuste dos weight e bias).
     
    Lista de Métodos Privados:
        N/A
    '''
    
    def __init__(self, qtd_inputs = 2, qtd_camadas = 3, qtd_saidas = 1, qtd_epocas = 1000, taxa_aprendizagem = 0.5):
        '''
        Método público que inicializa a instância da classe.
        Não há retorno para este método.
        
        Args:
            qtd_inputs(int): é a quantidade de variáveis de entrada para a MLP. O valor defalt é 2.
            qtd_camadas(int): é a quantidade de camadas da MLP. O valor default é 3.
            qtd_saidas(int): é a quantidade de saídas que serão geradas na MLP. O valor default é 1.
            qtd_epocas: é a quantidade de iterações que a rede realizará para aprender os padrões presentes nos
                     dados de entrada. O valor default é 1000.
            taxa_aprendizagem(float): é a taxa da velocidade na qual a descida gradiente ocorre. O valor
                                      default é 0.5.
            weight_1(list): são os pesos aplicados as camadas ocultas (hidden layers) da MLP.
            weight_2(list): são os pesos aplicados a última camada da MLP.
            bias_hidden(list): são os bias aplicados as camadas ocultas (hidden layers) da MLP.
            bias_output(list): é o bia aplicado a última camada da MLP.
            sig(list): é a função de ativação da MLP. O cálculo implementado corresponde a função sigmoid.
            dsig(list): é a derivada da função de ativação.     
        
        Returns:
            N/A
        '''
        # Atributos base da classe
        self.qtd_inputs = qtd_inputs
        self.qtd_camadas = qtd_camadas
        self.qtd_saidas = qtd_saidas
        self.qtd_epocas = qtd_epocas
        self.taxa_aprendizagem = taxa_aprendizagem
        
        # Matriz de pesos
        # O valor 0.5 apenas uniformiza a distribuição dos valores
        self.weight_1 = np.random.rand(self.qtd_camadas, self.qtd_inputs) - 0.5
        self.weight_2 = np.random.rand(self.qtd_saidas, self.qtd_camadas) - 0.5
        
        # Matriz de bias
        # O valor 0.5 apenas uniformiza a distribuição dos valores
        self.bias_hidden = np.random.rand(self.qtd_camadas, 1) - 0.5
        self.bias_output = np.random.rand(self.qtd_saidas, 1) - 0.5
                
        # Função de ativação (sigmoide) e sua derivada
        self.sig = lambda x: 1/(1+np.exp(-x))
        self.dsig = lambda y: y*(1.0-y)
    
    def calculate_error(self, saida_final, y_train):
        '''
        Método público que calcula os erros do output e das hidden layer. O cálculo corresponde a diferença
        entre os valores y de treino e os valores do cálculo da saída da MLP.
        Retorna os erros das camadas ocultas e da última camada (camada output).
        
        Args:
            saida_final(list): é uma lista contendo os resultados do cálculo da saída da MLP após a aplicação
                               da função de ativação.
            y_train(list): é uma lista contendo os valores das variáveis resultados a serem preditas.
              
        Returns:
            erro_out(list): é uma lista contendo o erro calculado da camada de saída.
            
            erro_oculto(list): é uma lista contendo os erros calculados das camadas ocultas.
        '''
        # Calcula o erro do output
        erro_out = y_train - saida_final
        
        # Calcula o erro da hidden layer
        erro_oculto = np.dot(self.weight_2.T, erro_out)
        return erro_out, erro_oculto
    
    def backpropagation(self, erro_out, erro_oculto, saida_final, saida_oculta, x_train_2d):
        '''
        Método público que realiza a aprendizagem da rede, ajustando os pesos (weights) e bias de cada neurônio.
        O método utilizado é o backpropagation.
        Não há returno para este método.
        
        Args:
            erro_out(list): é uma lista contendo o erro calculado da camada de saída.
            
            erro_oculto(list): é uma lista contendo os erros calculados das camadas ocultas.
            
            saida_final(list): é uma lista contendo os resultados do cálculo da saída da MLP após a aplicação
                               da função de ativação.
            
            saida_oculta(list): é uma lista contendo os resultados do cálculo das camadas ocultas após a aplicação
                               da função de ativação.
            
            x_train_2d(list): é uma lista contendo os valores de treino em duas dimensões (necessário para realizar
                              as operações de ajuste).
              
        Returns:
            N/A
        '''
        # Ajusta os pesos do output (a partir do delta) com o gradiente da curva sigmoide
        self.weight_2 += self.taxa_aprendizagem*(np.dot((erro_out*(self.dsig(saida_final))),
                                                        np.transpose(saida_oculta)))
        
        # Ajusta o bias do output (a partir do delta) com o gradiente da curva sigmoide
        self.bias_output += self.taxa_aprendizagem*(erro_out*(self.dsig(saida_final)))
        
        # Ajusta os pesos da hidden layer (a partir do delta) com o gradiente da curva sigmoide
        self.weight_1 += self.taxa_aprendizagem*(np.dot((erro_oculto*(self.dsig(saida_oculta))),
                                                        np.transpose(x_train_2d)))
        
        # Ajusta o bias da hidden layer (a partir do delta) com o gradiente da curva sigmoide
        self.bias_hidden += self.taxa_aprendizagem*(erro_oculto*(self.dsig(saida_oculta)))
            
    def fit(self, x_train, y_train):
        '''
        Método público para realizar o treino da rede MLP.
        Não há retorno para este método.
        
        Args:
            x_train(list): é uma lista contendo os valores de input para a rede neural.
            
            y_train(list): é uma lista contendo os labels da saída da rede neural.
            
        Returns:
            N/A
        '''
        # Inicia as iterações (épocas) para realizar a aprendizagem da rede (ajustes nos weights e bias).
        for epoca in range(self.qtd_epocas):
            
            # Iterando sobre os samples da base de entrada. Ex: x_train:[1,1] / y_train:[0]
            for x_sample, y_sample in zip(x_train, y_train):
            
                # Transforma a lista de entrada (x_sample) em uma lista de 2 dimensões
                x_train_2d = np.array(x_sample, ndmin=2).T
        
                # Calcula o output dos neurônios da hidden layer
                saida_oculta = self.sig(np.add((np.dot(self.weight_1, x_train_2d)), self.bias_hidden))
        
                # Calcula o output final (y) da rede neural
                saida_final = self.sig(np.add((np.dot(self.weight_2, saida_oculta)), self.bias_output))
        
                # Calcula o erro e realiza o método de backpropagation
                erro_out, erro_oculto = self.calculate_error(saida_final, y_sample)
                self.backpropagation(erro_out, erro_oculto, saida_final, saida_oculta, x_train_2d)
       
    def predict(self, x_test):
        '''
        Método público que prediz o resultado do valor informado conforme treino realizado na rede neural
        com o método .fit().
        Retorna a label correspondente ao valor de entrada.
        
        Args:
            x_test(list): é uma lista que corresponde aos valores de entrada que se deseja realizar a predição.
        
        Return:
            saida_final_discretizada = corresponde ao resultado da predição, sendo que retorna 1 para o caso do
            resultado da função de ativação ser maior ou igual a 0.5. E retorna 0 quando o resultado da função
            de ativação é menor a 0.5.
        '''
        # Transforma a lista de entrada (x_test) em uma lista de 2 dimensões
        x_test_2d = np.array(x_test, ndmin=2).T
        
        # Calcula o output dos neurônios da hidden layer
        saida_oculta = self.sig(np.add((np.dot(self.weight_1, x_test_2d)), self.bias_hidden))
        
        # Calcula o output final (y) da rede neural
        saida_final = self.sig(np.add((np.dot(self.weight_2, saida_oculta)), self.bias_output))
        
        # Discretiza a variável de saída
        saida_final_discretizada = np.round(saida_final, 0)
        
        return saida_final_discretizada

### Realização dos testes da classe criada (MLP)

#### Caso de Teste 3: Testando a Porta Lógica XOR

In [12]:
# Instanciando a MLP a partir do código criado
MLP = MultilayersPerceptron()

In [13]:
# Populando os valores de entrada da porta lógica XOR
x_train = np.array([[0,0],[0,1],[1,0],[1,1]])

# Populando os valores de saída da porta lógica XOR
y_train = np.array([[0],[1],[1],[0]])

In [14]:
# Realizando o treino da MLP
MLP.fit(x_train, y_train)

In [15]:
# Testando o resultado para o caso [0,0]
x_test = np.array([[0, 0]])
valor_predito = MLP.predict(x_test)
print('Valor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [0,1]
x_test = np.array([[0, 1]])
valor_predito = MLP.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [1,0]
x_test = np.array([[1, 0]])
valor_predito = MLP.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

# Testando o resultado para o caso [1,1]
x_test = np.array([[1, 1]])
valor_predito = MLP.predict(x_test)
print('\nValor predito de', x_test, 'é:', valor_predito)

Valor predito de [[0 0]] é: [[0.]]

Valor predito de [[0 1]] é: [[1.]]

Valor predito de [[1 0]] é: [[1.]]

Valor predito de [[1 1]] é: [[0.]]


### Desafio 3: Implementação das Portas Lógicas OR, AND e XOR com o TensorFlow 

In [16]:
import tensorflow as tf # Utilizado para criar a rede neural
import time # Utilizado para medir o desempenho do código em relação ao tempo de execução (treino) 

#### Classe TensorFlowPortasLogicas (MLP) para trabalhar com os casos de testes OR, AND e XOR

In [17]:
class TensorFlowPortasLogicas():
    '''
    Essa classe contém a implementação de uma rede neural para identificar portas lógicas, a partir da biblioteca
    TensorFlow.
    
    Lista de Atributos:
        porta_logica_entrada: são as entradas da porta lógica para realizar o treinamento da rede.
        
        porta_logica_saida: são as saídas da porta lógica para ajustar o treinamento da rede.
        
        qtd_epocas: é a quantidade de iterações que a rede realizará para aprender os padrões presentes nos
                     dados de entrada. 
                     
        taxa_aprendizagem: é a taxa da velocidade na qual a descida gradiente ocorre.              
    
    Lista de Métodos Públicos:
        __init__: inicializa as variáveis da classe.
        perform_training: instancia as variáveis necessárias no tensorflow e realizar o treinamento da rede.
     
    Lista de Métodos Privados:
        N/A
    '''
    
    def __init__(self, porta_logica_entrada, porta_logica_saida, qtd_epocas = 50000, taxa_aprendizagem = 0.01):
        '''
        Método público que inicializa a instância da classe.
        Não há retorno para este método.
        
        Args:
            porta_logica_entrada: são as entradas da porta lógica para realizar o treinamento da rede.
            porta_logica_saida: são as saídas da porta lógica para ajustar o treinamento da rede.
            qtd_epocas: é a quantidade de iterações que a rede realizará para aprender os padrões presentes nos
                     dados de entrada. O valor defalt é 16000.
            taxa_aprendizagem: é a taxa da velocidade na qual a descida gradiente ocorre. O valor defalt é 0.01.
                    
        Returns:
            N/A
        '''
        self.porta_logica_entrada = porta_logica_entrada
        self.porta_logica_saida = porta_logica_saida
        self.qtd_epocas = qtd_epocas
        self.taxa_aprendizagem = taxa_aprendizagem

    
    def perform_training(self):
        '''
        Método público que inicializa as instâncias do tensorflow, definindo a arquitetura da rede neural, e
        realiza o seu treinamento.
        Não há retorno para este método.
        
        Args:
            N/A
                    
        Returns:
            N/A
        '''
        
        # Configuração dos placeholders (espaço reservado para processamente futuro).
        tf_input = tf.placeholder(tf.float32, shape=[4,2], name = 'x_input')
        tf_output = tf.placeholder(tf.float32, shape=[4,1], name = 'y_input')
    
        # Configuração dos variables (espaço reservado para as variáveis a serem derivadas no modelo).
        tf_porta_input = tf.Variable(tf.random_uniform([2,2], -1, 1), name = "porta_input")
        tf_porta_output = tf.Variable(tf.random_uniform([2,1], -1, 1), name = "porta_output")
        
        # Configuração dos bias para ajuste na aprendizagem.
        tf_bias_1 = tf.Variable(tf.zeros([2]), name = "bias_1")
        tf_bias_2 = tf.Variable(tf.zeros([1]), name = "bias_2")
        
        # Configuração o resultado da saída da camada oculta (única).
        with tf.name_scope("hidden_layer_1") as scope:
            saida_oculta = tf.sigmoid(tf.matmul(tf_input, tf_porta_input) + tf_bias_1)
        
        # Configuração o resultado da saída da última camada (output).
        with tf.name_scope("out_layer") as scope:
            saida_final = tf.sigmoid(tf.matmul(saida_oculta, tf_porta_output) + tf_bias_2)
        
        # Configuração da função de perda, utilizada para otimizar e minimizar o erro do modelo (função de custo).
        # A método .reduce_mean efetua o somatório de matrizes, ignorando o limite das dimensões.
        with tf.name_scope("cost_function") as scope:
            cost_function = tf.reduce_mean(( (tf_output * tf.log(saida_final)) + 
                ((1 - tf_output) * tf.log(1.0 - saida_final)) ) * -1)
        
        # Configuração da aprendizagem da rede. Utilizando o método Gradient Descent para otimizar o valor
        # das variáveis (pesos e bias).
        with tf.name_scope("train") as scope:
            training_phase = tf.train.GradientDescentOptimizer(self.taxa_aprendizagem).minimize(cost_function)

        # Inicialização das variáveis definidas no TF.
        init = tf.global_variables_initializer()
        
        # Criação da sessão do TF.
        with tf.Session() as sess:
            
            # Definição dos logs para plotagem no TensorBoard.
            # Para acessar o TensorBoard basta exercutar no terminal (tensorboard --logdir==training:your_log_dir
            # --host=127.0.0.1) onde 'your_log_dir' é o endereço da pasta de log. Após isso, abra o browser com a 
            # url 127.0.0.1
            writer = tf.summary.FileWriter("./logs/portas_logicas_logs", sess.graph)
            
            # Roda a sessão do TF (inicialização das variáveis).
            sess.run(init)
            
            # Inicia a contagem do tempo do treinamento da rede.
            start_counting = time.clock()
            
            # Iteração da aprendizagem, conforme a quantidade de épocas definidas.
            for epoca in range(self.qtd_epocas):
                
                # Inicializa a fase de treinamento do modelo.
                # O parâmetro feed_dict atribui aos placeholders às entradas e saída da porta lógica.
                sess.run(training_phase, feed_dict={tf_input: self.porta_logica_entrada,
                                                   tf_output: self.porta_logica_saida})
                
                # Imprime os resultados do treino como forma de avaliação do modelo (da rede neural), a cada 1000
                # épocas.
                if epoca % 1000 == 0:
                    
                    print('\nÉpoca: ', epoca)
                    print('Valor previsto (hipótese): \n', sess.run(saida_final,
                                                           feed_dict={tf_input: self.porta_logica_entrada,
                                                                      tf_output: self.porta_logica_saida}))
                    print('Custo: ', sess.run(cost_function, feed_dict={tf_input: self.porta_logica_entrada,
                                                                        tf_output: self.porta_logica_saida}))
                    print('\nPeso 1: ', sess.run(tf_porta_input), '\nBias 1: ', sess.run(tf_bias_1),
                          '\nPeso 2: ', sess.run(tf_porta_output), '\nBias 2: ', sess.run(tf_bias_2))
                    print('\n---------------------------------------------------------------')
            
            # Finaliza a contagem do tempo do treinamento da rede.
            end_counting = time.clock()
            
            # Imprime o tempo de treinamento na tela
            print('Tempo para Treinamento:', end_counting - start_counting)

### Realização dos testes da classe criada (TensorFlowPortasLogicas)

#### Algumas observações quanto ao exercício:

##### 1- Quanto à validação do modelo, há várias maneiras de testá-lo. Neste exercício, foi adotado um método visando a praticidade e debug, adicionando simplesmente um log (prints), conforme as 15 últimas linhas de código da classe TensorFlowPortasLogicas. Neste log, são apresentadas, a cada 1000 épocas, os valores aprendidos (previstos), o resultado da função de custo e os pesos e bias da rede.
##### 2- Os valores preditos podem ser observados na variável printada 'Valor previsto (hipótese)'. Os valores que tendem a 0, correndepondem à saída lógica 0, e os valores que tendem a 1, correspondem à saída lógica 1.

#### Caso de Teste 1: Testando a Porta Lógica OR

In [18]:
# Definindo as entradas e saídas da porta OR
porta_OR_input = [[0,0],[0,1],[1,0],[1,1]]
porta_OR_output = [[0],[1],[1],[1]]

In [19]:
# Instanciando a rede neural a partir do código criado
TFPL_OR = TensorFlowPortasLogicas(porta_OR_input, porta_OR_output, qtd_epocas=25000)

In [20]:
# Realizando o treinamento e observando os resultados
TFPL_OR.perform_training()

Instructions for updating:
Colocations handled automatically by placer.


/home/modesto/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:105: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead



Época:  0
Valor previsto (hipótese): 
 [[0.5837669 ]
 [0.59141344]
 [0.60153645]
 [0.6085245 ]]
Custo:  0.601684

Peso 1:  [[ 0.48071033  0.8830771 ]
 [ 0.13062097 -0.4731872 ]] 
Bias 1:  [ 2.5748176e-04 -2.0900819e-05] 
Peso 2:  [[ 0.7378626 ]
 [-0.06453301]] 
Bias 2:  [0.00154361]

---------------------------------------------------------------

Época:  1000
Valor previsto (hipótese): 
 [[0.7290536 ]
 [0.748781  ]
 [0.77655333]
 [0.79014695]]
Custo:  0.5208923

Peso 1:  [[ 0.7570604   0.9179756 ]
 [ 0.43415296 -0.43364105]] 
Bias 1:  [ 0.01066805 -0.00345365] 
Peso 2:  [[1.168402  ]
 [0.21011738]] 
Bias 2:  [0.29763186]

---------------------------------------------------------------

Época:  2000
Valor previsto (hipótese): 
 [[0.71547514]
 [0.76007247]
 [0.7896611 ]
 [0.8152848 ]]
Custo:  0.4929113

Peso 1:  [[ 1.0064741   0.9698114 ]
 [ 0.72075    -0.37322003]] 
Bias 1:  [-0.14145954 -0.02254883] 
Peso 2:  [[1.440834  ]
 [0.24924411]] 
Bias 2:  [0.12936196]

----------------------


Época:  24000
Valor previsto (hipótese): 
 [[0.08254721]
 [0.97436416]
 [0.9768618 ]
 [0.9910306 ]]
Custo:  0.036136076

Peso 1:  [[4.311522   1.516408  ]
 [4.401211   0.32141528]] 
Bias 1:  [-2.3654652  -0.51058966] 
Peso 2:  [[7.5087967]
 [0.6310024]] 
Bias 2:  [-3.289479]

---------------------------------------------------------------
Tempo para Treinamento: 13.186406


/home/modesto/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:130: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


#### Caso de Teste 2: Testando a Porta Lógica AND

In [21]:
# Definindo as entradas e saídas da porta OR
porta_AND_input = [[0,0],[0,1],[1,0],[1,1]]
porta_AND_output = [[0],[0],[0],[1]]

In [22]:
# Instanciando a rede neural a partir do código criado
TFPL_AND = TensorFlowPortasLogicas(porta_AND_input, porta_AND_output, qtd_epocas=25000)

In [23]:
# Realizando o treinamento e observando os resultados
TFPL_AND.perform_training()

/home/modesto/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:105: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead



Época:  0
Valor previsto (hipótese): 
 [[0.39183986]
 [0.36875683]
 [0.36972952]
 [0.3479735 ]]
Custo:  0.6186541

Peso 1:  [[0.11007363 0.92664754]
 [0.7522428  0.07313229]] 
Bias 1:  [0.00017082 0.00012649] 
Peso 2:  [[-0.5077678 ]
 [-0.36893594]] 
Bias 2:  [-0.00119987]

---------------------------------------------------------------

Época:  1000
Valor previsto (hipótese): 
 [[0.28520995]
 [0.2689007 ]
 [0.27093607]
 [0.25514153]]
Custo:  0.58272576

Peso 1:  [[-0.00441001  0.8408166 ]
 [ 0.6246221   0.00092035]] 
Bias 1:  [0.0853378  0.06797115] 
Peso 2:  [[-0.54578024]
 [-0.36633593]] 
Bias 2:  [-0.44484556]

---------------------------------------------------------------

Época:  2000
Valor previsto (hipótese): 
 [[0.27112663]
 [0.2607958 ]
 [0.26616618]
 [0.25563124]]
Custo:  0.57298213

Peso 1:  [[-0.13808     0.765145  ]
 [ 0.4812666  -0.06672297]] 
Bias 1:  [0.11706702 0.094145  ] 
Peso 2:  [[-0.48987448]
 [-0.23543762]] 
Bias 2:  [-0.6064001]

-----------------------------


Época:  24000
Valor previsto (hipótese): 
 [[0.0024185 ]
 [0.04102288]
 [0.04614927]
 [0.9006903 ]]
Custo:  0.049037844

Peso 1:  [[-2.6689727  2.011903 ]
 [-2.972057   1.5133824]] 
Bias 1:  [ 3.8108501 -1.9691448] 
Peso 2:  [[-6.3579493]
 [ 4.1028123]] 
Bias 2:  [-0.304404]

---------------------------------------------------------------
Tempo para Treinamento: 13.281045000000002


/home/modesto/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:130: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead


#### Caso de Teste 3: Testando a Porta Lógica XOR

In [27]:
# Definindo as entradas e saídas da porta OR
porta_XOR_input = [[0,0],[0,1],[1,0],[1,1]]
porta_XOR_output = [[0],[1],[1],[0]]

In [28]:
# Instanciando a rede neural a partir do código criado
TFPL_XOR = TensorFlowPortasLogicas(porta_XOR_input, porta_XOR_output, qtd_epocas=100000)

In [29]:
# Realizando o treinamento e observando os resultados
TFPL_XOR.perform_training()

/home/modesto/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:105: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead



Época:  0
Valor previsto (hipótese): 
 [[0.49218696]
 [0.5011094 ]
 [0.5011969 ]
 [0.5097547 ]]
Custo:  0.6930446

Peso 1:  [[ 0.52982473 -0.1925746 ]
 [-0.17565025 -0.7368393 ]] 
Bias 1:  [-3.0109704e-06 -3.8991820e-06] 
Peso 2:  [[ 0.18622473]
 [-0.24871302]] 
Bias 2:  [-1.0668039e-05]

---------------------------------------------------------------

Época:  1000
Valor previsto (hipótese): 
 [[0.49071705]
 [0.49997103]
 [0.4998046 ]
 [0.5086337 ]]
Custo:  0.69301504

Peso 1:  [[ 0.5267533  -0.20573041]
 [-0.17537548 -0.7409021 ]] 
Bias 1:  [-0.00253027 -0.00464482] 
Peso 2:  [[ 0.18130273]
 [-0.25387567]] 
Bias 2:  [-0.00102963]

---------------------------------------------------------------

Época:  2000
Valor previsto (hipótese): 
 [[0.49046275]
 [0.5000085 ]
 [0.4997077 ]
 [0.5087628 ]]
Custo:  0.69298565

Peso 1:  [[ 0.52382606 -0.21972345]
 [-0.17511591 -0.74553084]] 
Bias 1:  [-0.00484136 -0.00986068] 
Peso 2:  [[ 0.17836592]
 [-0.25845006]] 
Bias 2:  [0.00146714]

----------


Época:  24000
Valor previsto (hipótese): 
 [[0.43682268]
 [0.5088979 ]
 [0.50821596]
 [0.54054755]]
Custo:  0.6760593

Peso 1:  [[ 0.4525553  -1.2471633 ]
 [-0.20414639 -1.4189315 ]] 
Bias 1:  [-0.04520177 -0.31261137] 
Peso 2:  [[ 0.13953573]
 [-1.090604  ]] 
Bias 2:  [0.13849719]

---------------------------------------------------------------

Época:  25000
Valor previsto (hipótese): 
 [[0.42603007]
 [0.5113099 ]
 [0.5111152 ]
 [0.54523647]]
Custo:  0.6712739

Peso 1:  [[ 0.44677857 -1.3771833 ]
 [-0.20894371 -1.5282134 ]] 
Bias 1:  [-0.04657162 -0.31224063] 
Peso 2:  [[ 0.13778944]
 [-1.2272456 ]] 
Bias 2:  [0.15323676]

---------------------------------------------------------------

Época:  26000
Valor previsto (hipótese): 
 [[0.41320473]
 [0.51434994]
 [0.5146642 ]
 [0.55048597]]
Custo:  0.6654399

Peso 1:  [[ 0.44038704 -1.5177279 ]
 [-0.21442401 -1.6494615 ]] 
Bias 1:  [-0.0478606  -0.29924837] 
Peso 2:  [[ 0.13633284]
 [-1.3798703 ]] 
Bias 2:  [0.17019944]

-----------------


Época:  48000
Valor previsto (hipótese): 
 [[0.08054471]
 [0.6289438 ]
 [0.6747675 ]
 [0.63346857]]
Custo:  0.48618636

Peso 1:  [[-0.35937965 -4.6248336 ]
 [-1.1135079  -4.6784616 ]] 
Bias 1:  [0.1429333 0.8100362] 
Peso 2:  [[ 1.2112359]
 [-4.8815   ]] 
Bias 2:  [0.29477522]

---------------------------------------------------------------

Época:  49000
Valor previsto (hipótese): 
 [[0.07862177]
 [0.63064617]
 [0.6845651 ]
 [0.62767524]]
Custo:  0.47746378

Peso 1:  [[-0.43401912 -4.7050157 ]
 [-1.2056855  -4.766301  ]] 
Bias 1:  [0.24467602 0.8479845 ] 
Peso 2:  [[ 1.3958753]
 [-4.9847503]] 
Bias 2:  [0.24592349]

---------------------------------------------------------------

Época:  50000
Valor previsto (hipótese): 
 [[0.07744366]
 [0.63287926]
 [0.69532704]
 [0.62057555]]
Custo:  0.4676388

Peso 1:  [[-0.51258177 -4.7814612 ]
 [-1.2943208  -4.851677  ]] 
Bias 1:  [0.3722989 0.889254 ] 
Peso 2:  [[ 1.5923492]
 [-5.088995 ]] 
Bias 2:  [0.18646348]

-------------------------------


Época:  73000
Valor previsto (hipótese): 
 [[0.04377264]
 [0.93265873]
 [0.93238014]
 [0.1218843 ]]
Custo:  0.07861677

Peso 1:  [[-3.4764557 -5.9585094]
 [-3.4849179 -6.039943 ]] 
Bias 1:  [5.0241895 2.1275992] 
Peso 2:  [[ 6.820617]
 [-7.863664]] 
Bias 2:  [-2.8334079]

---------------------------------------------------------------

Época:  74000
Valor previsto (hipótese): 
 [[0.04194837]
 [0.93663293]
 [0.93636423]
 [0.113989  ]]
Custo:  0.07377352

Peso 1:  [[-3.5365238 -5.985342 ]
 [-3.5447798 -6.0646887]] 
Bias 1:  [5.121096  2.1555908] 
Peso 2:  [[ 6.9479556]
 [-7.95286  ]] 
Bias 2:  [-2.9079134]

---------------------------------------------------------------

Época:  75000
Valor previsto (hipótese): 
 [[0.04024613]
 [0.94021064]
 [0.9399529 ]
 [0.10692509]]
Custo:  0.069435015

Peso 1:  [[-3.5929286 -6.0109625]
 [-3.6010094 -6.088341 ]] 
Bias 1:  [5.2119784 2.181857 ] 
Peso 2:  [[ 7.0685687]
 [-8.038753 ]] 
Bias 2:  [-2.9782202]

---------------------------------------------


Época:  98000
Valor previsto (hipótese): 
 [[0.01998027]
 [0.9752152 ]
 [0.9751153 ]
 [0.04092009]]
Custo:  0.028065026

Peso 1:  [[-4.3550854 -6.3984365]
 [-4.361416  -6.45097  ]] 
Bias 1:  [6.4273224 2.5303488] 
Peso 2:  [[ 8.811349]
 [-9.419851]] 
Bias 2:  [-3.9648898]

---------------------------------------------------------------

Época:  99000
Valor previsto (hipótese): 
 [[0.0195333 ]
 [0.9758563 ]
 [0.9757587 ]
 [0.03977833]]
Custo:  0.027324408

Peso 1:  [[-4.375681  -6.409942 ]
 [-4.381937  -6.4619374]] 
Bias 1:  [6.459741 2.539501] 
Peso 2:  [[ 8.861604]
 [-9.463162]] 
Bias 2:  [-3.9925892]

---------------------------------------------------------------
Tempo para Treinamento: 55.28695800000001


/home/modesto/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:130: DeprecationWarning: time.clock has been deprecated in Python 3.3 and will be removed from Python 3.8: use time.perf_counter or time.process_time instead
